### Variables 
@apiurl = http://localhost:8080/api
@tokenUserTest= RI_t9kSolJXH6CJvvtJeF88UhgRPRHdXZ7cMUnTMDnk=

@tokenUserAdmin = xdHP60lG0VL0hHIr6jE_wpbarF1ZOtrVJlJ9aGPniiM=


@tokenUserTest1 = oBefzKUQ45dit8vseP9NWIH1eUBIEGv-6SXxQfXaIns=
### USER 

### Create Token Test
POST {{apiurl}}/users/token HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "12345"
}


### Create Token Admin
POST {{apiurl}}/users/token HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Create Token User1
POST {{apiurl}}/users/token HTTP/1.1
Content-Type: application/json

{
    "username": "Test99",
    "password": "Test_999"
}


### Listen User
GET {{apiurl}}/users/listen HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Create User Francisco
@inviteCodeUser = "9303d-7a2de"
POST {{apiurl}}/users  HTTP/1.1
Content-Type: application/json

{
    "username": "Test99",
    "email":"test99@gmail.com",
    "password": "Test_999",
    "inviteCode": {{inviteCodeUser}}
}


### User Details
@id = 1
@inviteCode = 9303d-7a2de
GET {{apiurl}}/users/{{id}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "username": "Francisco",
    "email":"email",
    "password": "12345",
    "inviteCode": {{inviteCode}}
}

### HOME Test
GET {{apiurl}}/home HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}



### HOME Admin
GET {{apiurl}}/home HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserAdmin}}



### Invite User
POST {{apiurl}}/users/invite  HTTP/1.1
Content-Type: application/json
Authorization: Bearer "DU7_ifPu4sKPwp4_EOQVVtTEIfdNUKsCHyF40QIzPNY="


### Logout User Test
POST {{apiurl}}/logout  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

### Logout User Admin
POST {{apiurl}}/logout  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserAdmin}}




### Channels

### Create Channel 
POST {{apiurl}}/channels/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "name":"Channel DAW",
    "type":"PUBLIC"
}

### Search channels (Sort Name) 
@Sort="name"
GET {{apiurl}}/channels?sort={{Sort}}HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}




### Channel by Id

GET {{apiurl}}/channels/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Search channels by name
@name = Channel
@sort = name
GET {{apiurl}}/channels?name={{name}}&sort={{sort}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Channels owned by user 
@id = 1
GET {{apiurl}}/channels/user/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Channels user is member 
@sort = name
GET {{apiurl}}/channels/member={{name}}?sort={{sort}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Update Channel
@id = 1
@name = "Channel ISEL"
@type = "PRIVATE"
PATCH {{apiurl}}/channels/{{id}}/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "name":{{name}},
    "type":{{type}}
}


### Join Public Channel 
@id = 7
POST {{apiurl}}/channels/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserAdmin}}


### Create Private Channel Invite
POST {{apiurl}}/channels/4/private-invite HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "privacy": "READ_WRITE",
    "username": "admin"
}

### Reject Private Channel Invite
@invitecode1= 3ee9eb75-a6e9-45ea-8ee8-2411da236fbc
POST {{apiurl}}/channels/4/invite/{{invitecode1}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer rNtzk8juF1kCLbfTPym-MplQiUKMVL1hxyV14rM0esE=

{
    "status": "REJECT"
}

### Accept Private Channel Invite
@invitecode2= df2658f1-42a7-4ded-b3d6-5f0b891306e5
POST {{apiurl}}/channels/4/invite/{{invitecode2}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer rNtzk8juF1kCLbfTPym-MplQiUKMVL1hxyV14rM0esE=

{
    "status": "ACCEPT"
}

### Leave Channel
@id = 1
POST {{apiurl}}/channels/{{id}}/leave HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "privacy":"READ_WRITE",
    "username":"Rita99"
}


### GET Invitations Received
GET {{apiurl}}/channels/invites/received HTTP/1.1
Content-Type: applicatio/json
Authorization: Bearer {{tokenUserAdmin}}  


### GET Invitations Sent
GET {{apiurl}}/channels/invites/sent?offset=2&limit=2 HTTP/1.1
Content-Type: applicatio/json
Authorization: Bearer {{tokenUserTest}}  



### Leave Channel
@id = 5
POST {{apiurl}}/channels/4/leave HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserAdmin}}



### Message

### Create/Send Message
POST {{apiurl}}/channels/13/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}

{
    "text":"DAW 20"
}


### View Messages
@id = 1
GET {{apiurl}}/channels/{{id}}/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}


### Get Message By Id 
GET {{apiurl}}/channels/4/messages/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}



###  Delete Message
@channelId = 4
@messageId= 4
DELETE  {{apiurl}}/channels/{{channelId}}/messages/{{messageId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUserTest}}



